src/components/Common/atoms/Items/NoticeItem/index.tsx
src/utils/dateRegex.ts
src/utils/todayDate.ts

공통부분 추가,수정
날짜관련 함수 생성, noticeItem 에 적용

Add 날짜관련 함수

---

src/assets/data/SidebarMenuData.ts
src/components/Common/atoms/Buttons/LogoutButton/index.tsx
src/components/Common/organisms/Sidebar/index.tsx
src/components/SignIn/organisms/SignInForm/index.tsx
src/pages/home.tsx
src/pages/index.tsx

공통부분 수정
기존 homePage url 에 프로모션페이지가 들어가게되면서 homePage url 을 home 으로 변경했습니다

Fix homePage url

---

src/api/member.ts
src/components/ChangePasswd/organisms/ChangePasswdForm/index.tsx
src/components/Common/atoms/Inputs/AuthInput/index.tsx
src/components/Common/atoms/Inputs/AuthInput/style.ts
src/components/SignUp/atoms/Wrapper/style.ts
src/pages/changePasswd.tsx
src/types/Forms.ts
src/utils/Libs/requestUrls.ts

비밀번호 변경페이지 퍼블리싱,기능구현했습니다
-darkMode
- 전체입력

Add 비밀번호 변경 페이지

---

src/components/Common/atoms/Items/NoticeItem/index.tsx
src/components/Common/atoms/Items/NoticeItem/style.ts
src/components/Home/organisms/NoticeBoard/index.tsx
src/types/Items.ts

공통부분 수정
공지사항 게시글 onClick 이벤트를위해 id 속성 추가했습니다

Update : noticeItem 속성

---

.prettierrc
src/styles/globals.tsx

- global style에서 `--SYSTEM_ERROR` 가 잘못된 색이 지정되어 수정했습니다
- global style에서 `--SYSTEM_ERROR` 의 색을 수정했습니다
- github에서 pr 리뷰할 때 보기 쉽도록 Prettierrc의 useTabs를 false로 바꾸었습니다

global style 수정

---

src/styles/globals.tsx

- #18 에서 global style 문제가 해결된 줄 알았으나 코드 중에 각 변수마다 세미콜론을 쓰지 않아 style이 적용이 되지 않아서 다시 수정합니다
- body의 background color가 잘 적용되지 않아 body style을 수정했습니다
- darkTheme의 css변수 5개에 세미콜론을 붙였습니다
- body에 background color를 추가했습니다

Fix global style

---

src/components/Common/atoms/Items/NoticeItem/style.ts

공통부분 수정
공지사항 item width 수정했습니다

Fix  noticeItem width

---

src/components/Home/organisms/NoticeBoard/style.ts
src/components/Home/organisms/Profile/style.ts
src/components/Home/organisms/TimeBoard/index.tsx
src/components/Home/organisms/TimeBoard/style.ts

homPage 반응형 수정
단위를 px -> vw 로 수정했습니다
안쓰는 속성제거했습니다

Fix  homePage 반응형 단위

---

src/components/Common/atoms/Buttons/AuthButton/index.tsx
src/components/Common/atoms/Buttons/AuthButton/style.ts
src/components/Common/atoms/Inputs/AuthInput/style.ts
src/components/Common/atoms/Wrappers/AuthWrapper/style.ts
src/components/SignIn/organisms/SignInForm/index.tsx
src/components/SignIn/organisms/SignInForm/style.ts
src/components/SignUp/atoms/Wrapper/style.ts
src/components/SignUp/molecules/EmailCheck/style.ts
src/components/SignUp/molecules/StepHeader/style.ts
src/components/SignUp/molecules/StuInfo/style.ts
src/types/Buttons.ts

로그인, 회원가입, 비밀번호찾기 페이지 반응형
- 로그인 페이지 
- 회원가입 페이지 1단계
- 2단계
- 3단계
- 비밀번호 찾기 페이지

Add  signin, signup, changePasswd 반응형

---

src/components/Home/atoms/PenaltyItem/style.ts
src/components/Home/molecules/ApplyBox/index.tsx
src/components/Home/molecules/ApplyBox/style.ts
src/components/Home/molecules/PenaltyModal/style.ts
src/components/Home/organisms/MealBoard/style.ts
src/components/Home/organisms/NoticeBoard/style.ts
src/components/Home/organisms/Profile/style.ts
src/components/Home/organisms/TimeBoard/style.ts
src/components/Home/templates/HomeTemplates/style.ts

비율이 다른 노트북(ex 그램)으로봤을떄 화면이 이상해지는 문제
height 단위를 px -> vh 로 변경
스크롤바 커스텀

Fix  homPage responsive

---

src/components/Common/molecules/CommonCheckModal/index.tsx
src/components/Common/molecules/CommonCheckModal/style.ts
src/components/Penalty/atoms/PenaltyListModalItem/index.tsx

Update  CommonDelModal naming

---

package.json
src/components/Home/organisms/TimeBoard/index.tsx
yarn.lock

홈페이지 이미지가 느리게 랜더링되는 문제
sharp 추가했습니다
priority 속성추가해서 이미지먼저 랜더링되게 설정했습니다

Update homPageImage rendering

---

src/styles/globals.tsx
src/utils/Config/Config.json
src/utils/Libs/apiClient.ts
src/utils/Libs/getRefresh.ts

apiClient 에 토큰재발급하는 url 설정과 baseHeader 오류
config.json 파일,오타 수정했습니다
apiClient 에 토큰재발급하는 url, bearer 설정했습니다
global style 잘못된 속성 수정했습니다

Fix  apiClient, global style

---

src/api/member.ts
src/api/selfStudy.ts
src/components/ChangePasswd/organisms/ChangePasswdForm/index.tsx
src/components/SignIn/organisms/SignInForm/index.tsx
src/components/SignUp/molecules/EmailCheck/index.tsx
src/components/SignUp/molecules/PasswordCheck/index.tsx
src/components/SignUp/molecules/StuInfo/index.tsx
src/utils/Libs/requestUrls.ts

로그인,회원가입,비밀번호 변경 페이지 기능구현
로그인,회원가입,비밀번호 변경 페이지 기능구현했습니다

Update 로그인,회원가입,비밀번호 변경 페이지

---

src/pages/home.tsx
src/pages/index.tsx
src/pages/signin.tsx
src/pages/signup.tsx
src/utils/Libs/getRefresh.ts
src/utils/Libs/getToken.ts

로그인 여부에따라 url 직접접근 막기
- getToken 에 RefeshToken 없는경우 추가했습니다
- signin, signup, promotion, homePage url 로그인 여부에따라 url 직접접근 막았습니다

Update : url 접근

---

src/api/member.ts
src/components/SignUp/molecules/StuInfo/index.tsx
src/components/SignUp/molecules/StuInfo/style.ts
src/pages/signin.tsx
src/pages/signup.tsx
src/utils/Libs/getRole.ts
src/utils/Libs/setToken.ts

요청을 보낼때 Bearer 을 계속 붙여줘야 되는 문제
토큰을 저장할떄 Bearer 을 넣어서 저장하도록했습니다
재발급 api Bearer 삭제했습니다
getRole 에서 Bearer 을 삭제하는 구문 추가했습니다

Fix  token Bearer

---

src/assets/json/role.json
src/types/Role.ts
src/utils/Libs/getRole.ts

Fix  getRole

---

next.config.js

next 13의 특성 상 외부 이미지를 불러오기 위해 도메인을 설정해야 합니다.
외부 이미지에 대한 모든 도메인을 허용했습니다.

🔀 Un-configured Host 문제 수정

---

src/pages/_app.tsx

토스트가 다크모드일떄 색적용이 안되는 문제
다크모드일때 다크모드색으로 변경되게 했습니다.
SWRConfig 설정해서 포커스가 됬을때 재랜더링이 되게 설정했습니다.

Update : toast darkMode

---

package.json
src/components/Common/atoms/Calendar/index.tsx
src/components/Common/atoms/Calendar/style.ts
src/recoilAtoms/recoilAtomContainer.ts
yarn.lock

Calendar를 구현했습니다.
- 빨간색 : 현재 날짜
- 파란색 : 선택한 날짜
- 검은색 : hover한 날짜
```js
// component
import CalendarBox from 'components/Common/atoms/Calendar';
<CalendarBox />
// value
import { useRecoilState } from 'recoil';
import { selectedDate } from 'recoilAtoms/recoilAtomContainer';
const [date, setDate] = useRecoilState(selectedDate)
// date : 선택한 날짜 (기본 값 : new Date())
// setDate : 날짜 바꾸기 (달력에서 선택해도 날짜가 변경됩니다)

🔀 Portal 추가

---

src/api/massage.ts
src/api/selfStudy.ts
src/components/Home/organisms/MassageBoard/index.tsx
src/components/Home/organisms/NoticeBoard/index.tsx
src/components/Home/organisms/SelfStudyBoard/index.tsx

message, selfStudy api,board 리펙토링
message, selfStudy api,board 리펙토링했습니다
message, selfStudy 신청취소 202 처리했습니다
noticeBoard key 값 줬습니다

Fix message, selfStudy Board

---

src/components/Common/organisms/CommonHeader/index.tsx

query있는 공지사항 상세 페이지에서는 title을 못 불러오는 문제가 있었습니다
MenuData의 routerName이 현재 url에 포함되면 title을 불러오도록 수정했습니다

🔀Common Header title 개선

---

src/api/member.ts
src/components/ChangePasswd/organisms/ChangePasswdForm/index.tsx
src/components/Common/molecules/EmailCheck/index.tsx
src/pages/changePasswd.tsx
src/recoilAtoms/recoilAtomContainer.ts
src/utils/Libs/requestUrls.ts

패스워드 변경페이지에서 로그인 전후에따라 요청하는 url 이랑 인자값이 다름 
패스워드 변경페이지에서 로그인 전후에따라 요청하는 api 각각 추가했습니다.

Add : authPasswordChange api

---

src/middleware.ts
src/pages/home.tsx
src/pages/massage.tsx
src/pages/penalty.tsx
src/pages/selfstudy.tsx
src/pages/signin.tsx
src/pages/signup.tsx

middleware 로 url 직접접근 막기
middleware 로 url 직접접근 막았습니다
기존 ssr 에서 직접접근 처리한거 수정했습니다
인증페이지에서 ssr 제거했습니다.

Add middleware

---

src/components/Common/atoms/SEOHead/index.tsx
src/pages/404.tsx
src/pages/_document.tsx
src/pages/changePasswd.tsx
src/pages/home.tsx
src/pages/index.tsx
src/pages/massage.tsx
src/pages/penalty.tsx
src/pages/selfstudy.tsx
src/pages/signin.tsx
src/pages/signup.tsx

seo 작업
SEOHead 추가했습니다
signin, signup, 404, home, changePasswd, massage, penalty, selfstudy, promotion 페이지에 적용했습니다

Add : CEOHead

---

src/components/Common/atoms/SEOHead/index.tsx
src/components/SignIn/organisms/SignInForm/index.tsx
src/middleware.ts
src/pages/404.tsx
src/pages/changePasswd.tsx
src/pages/home.tsx
src/pages/index.tsx
src/pages/massage.tsx
src/pages/penalty.tsx
src/pages/selfstudy.tsx
src/pages/signin.tsx
src/pages/signup.tsx

middleware 에 비밀번호찾기 예외처리 추가, 리펙토링했습니다
SEOHead 설명태그 추가, 사진 변경하고 다른 page 들 text 변경했습니다.

Fix : middleware

---

src/pages/notice/[boardId].tsx
src/pages/notice/index.tsx

공지사항 페이지에 swr config 가 없어서 추가합니다

🔀 공지사항 페이지 swr config 추가

---

src/components/Common/atoms/Calendar/index.tsx
src/components/Common/atoms/Calendar/style.ts
src/components/Common/molecules/SearchFilter/index.tsx

Calendar style, SearchFilter 오타 수정
Calendar 화이트모드 달력날짜색 수정, SearchFilter 오타 수정

Calendar style, SearchFilter 오타 수정

---

src/components/Common/atoms/Calendar/style.ts

기상음악 페이지에서 달력의 반응형 디자인을 적용하기 위해 수정했습니다.
- width : 1920px
---
- width: 951px

🔀 Calendar style 수정

---

src/components/Home/organisms/MassageBoard/index.tsx
src/components/Home/organisms/NoticeBoard/index.tsx
src/components/Home/organisms/NoticeBoard/style.ts
src/components/Home/organisms/SelfStudyBoard/index.tsx
src/components/Home/organisms/TimeBoard/index.tsx
src/components/Promotion/templates/PromotionTemplates/style.ts
src/middleware.ts
src/pages/changePasswd.tsx
src/pages/index.tsx
src/pages/signin.tsx
src/pages/signup.tsx

프로모션 페이지 middleware 에 추가
ssr 이 필요없는페이지에 dynamic import 추가하여 csr 로 랜더링
공지사항 년월로 변경

Update Error HomePage, authPage

---

src/components/Common/organisms/Sidebar/index.tsx
src/pages/home.tsx
src/pages/massage.tsx
src/pages/notice/[boardId].tsx
src/pages/notice/index.tsx
src/pages/penalty.tsx
src/pages/selfstudy.tsx
src/pages/song.tsx

sidebar 를 ssr 환경에서 가져올 필요가없어서 csr 처리

Fix : SideBar : dynamic import

---

src/components/Common/atoms/Items/SidebarItem/index.tsx
src/components/Common/atoms/Items/SidebarItem/style.ts
src/components/Common/molecules/SidebarList/index.tsx
src/components/Common/molecules/SidebarList/style.ts
src/components/Common/organisms/Sidebar/index.tsx
src/components/Common/organisms/Sidebar/style.ts

Fix : SideBar

---

src/components/Home/organisms/SelfStudyBoard/index.tsx
src/components/Notice/molecules/ContentHeader/index.tsx
src/components/Notice/molecules/ListHeader/index.tsx
src/components/Notice/molecules/WriteForm/style.ts
src/components/Notice/organisms/NoticeEmpty/index.tsx
src/components/Notice/organisms/NoticeEmpty/style.ts
src/components/Notice/organisms/NoticeList/index.tsx
src/components/Notice/organisms/NoticeList/style.ts
src/components/Notice/templates/NoticeTemplate/style.ts
src/pages/notice/[boardId].tsx
src/pages/notice/index.tsx

- 공지사항 상세 component에서 수정, 삭제 권한 수정
- 공지사항 삭제 전 check modal 추가
- 간단한 font 크기, 색상 등 변경
- 공지사항 리스트 날짜 구분선 format 수정 (MM월 dd일 -> yyyy년 MM월)

🔀 공지사항 이슈 수정

---

src/api/music.ts
src/components/Song/molecules/NoticeModal/index.tsx
src/components/Song/molecules/SongForm/style.ts
src/components/Song/molecules/SongItem/index.tsx
src/components/Song/molecules/SongItem/style.ts
src/components/Song/organisms/SongList/style.ts
src/components/Song/organisms/SongModal/index.tsx
src/components/Song/template/style.ts
src/pages/_app.tsx
src/pages/song.tsx

- 자신이 신청한 기상 음악 삭제할 수 있게 수정
- 음악 item 간의 gap 추가
- 기상음악에서 발생하는 modal의 event bubbling 삭제

🔀 기상음악 이슈 수정

---

src/assets/svg/SearchIcon.tsx
src/components/Common/atoms/Inputs/AuthInput/index.tsx
src/components/Common/atoms/Inputs/AuthInput/style.ts
src/components/Common/atoms/Items/FilterItem/index.tsx
src/components/Common/molecules/SearchFilter/index.tsx
src/components/Common/molecules/SearchFilter/style.ts
src/components/Penalty/organisms/PenaltyTable/index.tsx
src/components/SelfStudy/organisms/SelfStudyTable/index.tsx
src/types/Filter.ts
src/types/Inputs.ts

SearchFilter 이슈 수정, AuthInput 적용
SearchFilter 버튼 클릭 안되는 이슈 수정, AuthInput 적용 
authinput

SearchFiler issue, authinput 적용

---

src/assets/svg/EllipsisVerticalIcon.tsx
src/assets/svg/index.ts
src/components/Penalty/atoms/PenaltyItem/Style.ts
src/components/Penalty/atoms/PenaltyItem/index.tsx
src/components/Penalty/molecules/PenaltyListModal/style.ts
src/components/Penalty/molecules/PenaltyRecordMenuModal/index.tsx
src/components/Penalty/molecules/PenaltyRecordMenuModal/style.ts
src/components/Penalty/molecules/PenaltyRecordModal/style.ts
src/components/Penalty/organisms/PenaltyTable/index.tsx
src/components/Penalty/organisms/PenaltyTable/style.ts
src/components/Penalty/templates/PenaltyTemplates/style.ts

PeanltyPage Response
규정위반 페이지 반응형 작업
|<img width="1440" alt="스크린샷 2023-04-05 오후 4 47 29" src="https://user-images.githubusercontent.com/86366459/230016298-f6e0e602-b596-42d3-bcaa-c6980fbbd1cd.png">|<img width="929" alt="스크린샷 2023-04-05 오후 4 48 01" src="https://user-images.githubusercontent.com/86366459/230016309-a0ebcdfe-7612-408f-86ab-5523832b4f91.png">|
| -----------| ----------- |
|<img width="376" alt="스크린샷 2023-04-05 오후 4 49 58" src="https://user-images.githubusercontent.com/86366459/230016320-f08083d6-e2e6-4328-8540-f3d9e8d427af.png">|<img width="375" alt="스크린샷 2023-04-05 오후 4 50 14" src="https://user-images.githubusercontent.com/86366459/230016323-0b014641-37c2-4556-9778-c449d094b0b8.png">|
| -----------| ----------- |

PeanltyPage Response

---

src/components/Home/organisms/NoticeBoard/index.tsx

공지사항리스트가 안보임
NoticeBoard 대괄호 제거했습니다.

Fix NoticeBoard 대괄호 제거

---

src/pages/_document.tsx

darkmode 상태일떄 새로고침하면 깜빡이는 현상
themeInitializerScript 를 정해줘 theme 를 미리 받도록 설정했습니다.

Update darkmode 설정

---

src/components/Common/molecules/SearchFilter/index.tsx

필터 사용성 수정
필터아이템 선택된거 다시 클릭시 취소되게 변경

Fix: searchFilter

---

src/components/Common/atoms/Buttons/DarkModeBtn/index.tsx
src/components/Common/atoms/Buttons/DarkModeBtn/style.ts
src/components/Home/molecules/ApplyBox/index.tsx
src/components/Home/molecules/ApplyBox/style.ts

다크모드버튼배경색이 디자인과 다름
인원수에따라 라인색변경
신청버튼 글자,배경색 에러
다크모드버튼배경색 디자인대로 고쳤습니다.
인원수에따라 라인색변경되게 했습니다.
신청버튼 글자,배경색 에러고쳤습니다.

Fix : DarkModeButton, ApplyBox

---

src/assets/svg/XmarkIcon.tsx
src/components/Common/atoms/Inputs/AuthInput/index.tsx
src/components/Home/atoms/MenuOption/style.ts
src/components/SignIn/organisms/SignInForm/index.tsx
src/middleware.ts
src/pages/home.tsx

홈페이지, 로그인 이슈들 고쳤습니다
bot 일떄 토큰삭제했습니다.
로그인 자동완성, x 아이콘 색상을 입력여부에따라 변경했습니다.
메뉴 border 삭제했습니다.
SWRConfig 에 채널톡 component 를 추가했습니다.

Fix Home, login Page Issues

---

src/components/Common/atoms/Calendar/index.tsx

달력의 시작 요일을 변경했습니다.
- 변경 전
- 변경 후
@HWANBINYOO @wjdalsths 형들 오늘 면접보느라 수고했습니다~

🔀 달력 요일 표기 변경

---

src/components/Common/atoms/Wrappers/CommonPageWrapper/style.ts
src/components/Home/organisms/Profile/style.ts
src/components/Home/organisms/TimeBoard/style.ts
src/components/Home/templates/HomeTemplates/style.ts

기존 홈페이지 Header Title 과 다른 Header TItle 높이가 안맞는문제
Page Contants Padding 값이 다 달라 페이지마다 간격이 안맞는문제
홈페이지 Header 높이 맞췄습니다.
CommonPageWrapper 를 만들었습니다.
before : 
after :

Add CommonPageWrapper

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml

PR과 더불어 Issue 작성할 때도 템플릿이 있으면 좋을 것 같습니다
| 파일 | 스크린샷 |
| ----- | ---------- |
| bug.yml |![image](https://github.com/Team-Ampersand/Dotori-client-v2/assets/87346613/32070e0e-ef6d-4720-abec-21631e0406d9) |
| feature.yml | ![image](https://github.com/Team-Ampersand/Dotori-client-v2/assets/87346613/be1ad4bb-2a13-4698-af04-1ea13cf0011d) |
템플릿에 추가하고 싶거나 삭제하고 싶은 것에 대해 comment 남겨주시면 되겠습니다.

[#192] :: 🔀 Issue 템플릿 만들기

---

src/components/Home/organisms/MassageBoard/index.tsx
src/components/Home/organisms/SelfStudyBoard/index.tsx

자습이나 안마의자 신청이 불가한경우에 불필요한 요청이 간다는 이슈
불필요한 요청을 없애고 toast 를 띄우도록 했습니다

Refector 안마, 자습 신청불가케이스  

---

src/api/stuInfo.ts
src/components/Common/atoms/Inputs/AuthInput/style.ts
src/components/StuInfo/molecules/EditRadioBtn/index.tsx
src/components/StuInfo/molecules/EditRadioBtn/style.ts
src/components/StuInfo/organisms/EditModal/index.tsx
src/components/StuInfo/organisms/EditModal/style.ts
src/components/StuInfo/organisms/StuInfoList/index.tsx
src/components/StuInfo/template/style.ts

<table><tr><th>
이슈
</th><th>
자료
</th></tr><tr><td>
학생정보 리스트에서 contents가 리스트 높이를 overflow 할 때 부자연스러운 디자인이 있었습니다. 
</td><td rowspan="2">
</td></tr><tr><td>
학생정보 리스트에서 content간의 간격이 좁아 보입니다.
</td></tr><tr><td>
학생 정보 수정 모달 디자인이 이상합니다.
</td><td rowspan="2">
</td></tr><tr><td>
학생 직책 수정이 잘 되지 않아요
</td></table>
https://github.com/Team-Ampersand/Dotori-client-v2/assets/87346613/50deea35-3cf4-4c05-8da2-d9f979c5adbd
https://github.com/Team-Ampersand/Dotori-client-v2/assets/87346613/327a9887-b165-4595-ad72-125f7ebc4501

[#157 #158 #169] :: 🔀 학생정보 페이지 이슈 해결

---

src/components/Common/atoms/Items/Custom500Text/Custom500Text.tsx
src/components/Common/atoms/Items/Custom500Text/style.ts
src/components/NotFound/organisms/NotFoundOrganisms/index.tsx
src/pages/404.tsx
src/pages/500.tsx

500 에러 페이지가 없음
- 500 페이지를 임시로 만들었습니다
- light mode
- dark mode

Add : 500 Page

---

src/components/Common/atoms/Wrappers/CommonPageWrapper/style.ts
src/components/Common/molecules/NullApplicationItem/style.ts
src/components/Common/molecules/SearchFilter/style.ts
src/components/Common/molecules/SidebarList/style.ts
src/components/Common/organisms/CommonHeader/style.ts
src/components/Common/organisms/NavigationDrawer/style.ts
src/components/Common/organisms/Sidebar/style.ts
src/components/Common/templates/AuthTemplates/style.ts
src/components/Common/templates/MainTemplates/style.ts
src/components/Home/molecules/ApplyBox/style.ts
src/components/Home/organisms/MealBoard/style.ts
src/components/Home/organisms/NoticeBoard/style.ts
src/components/Home/organisms/Profile/style.ts
src/components/Home/organisms/TimeBoard/style.ts
src/components/Home/templates/HomeTemplates/style.ts
src/components/Massage/organisms/MassageTable/style.ts
src/components/NotFound/organisms/NotFoundOrganisms/style.ts
src/components/Notice/templates/NoticeTemplate/style.ts
src/components/Penalty/molecules/PenaltyRecordModal/style.ts
src/components/Penalty/organisms/PenaltyTable/style.ts
src/components/Penalty/templates/PenaltyTemplates/style.ts
src/components/Promotion/molecules/DecsPart/style.ts
src/components/Promotion/molecules/LoadingPart/style.ts
src/components/Promotion/organisms/PromotionOrganisms/style.ts
src/components/Promotion/templates/PromotionTemplates/style.ts
src/components/SelfStudy/organisms/SelfStudyTable/style.ts
src/components/SelfStudy/templates/SelfstudyTemplates/style.ts

도토리웹사이트를 폰으로 접속하면 하단 내비게이션바가 사라지는 이슈
vh 대신 dvh 단위를써서 모바일에서도 하단 네이게이션바가 잘 나타나도록 했습니다

🔀 vh 반응형 단위 변경

---

src/components/Home/molecules/PenaltyModal/style.ts
src/components/Penalty/molecules/PenaltyListModal/style.ts

main페이지의 규정위반 모달의 style이 불일치하여 수정하였습니다.
penaltyModal의 style변경

🔀 규정위반 모달 style 수정

---

src/components/Notice/organisms/NoticeContent/style.ts

공지 글을 작성할 때 글 내용의 길이가 길어지면 넘어가는 버그를 수정했습니다.
overflow를 설정 해 줬습니다.

🔀 공지사항 ContentWrapper수정 & 제목 width 수정

---

src/components/Notice/molecules/ContentHeader/style.ts

🔀 공지사항 제목 길이 수정

---

src/components/Song/molecules/SongItem/index.tsx

기상음악 신청 시 몇몇의 섬네일이 보여지지 않는 현상이 있어서 수정했습니다.
| 작업 전 | 작업 후 |
|---|---|
| ![image](https://github.com/Team-Ampersand/Dotori-client-v2/assets/87346613/2d4d8406-81b2-4a79-bd26-88e5b944988f) | ![image](https://github.com/Team-Ampersand/Dotori-client-v2/assets/87346613/851e03d3-3d2d-44f8-81aa-4f2442b058aa) |
| ![image](https://github.com/Team-Ampersand/Dotori-client-v2/assets/87346613/ef6ba84c-28f4-47f5-92cf-538435104ca5) | ![image](https://github.com/Team-Ampersand/Dotori-client-v2/assets/87346613/419f83df-03f1-48d7-8a18-20327b33964e) |
| ![image](https://github.com/Team-Ampersand/Dotori-client-v2/assets/87346613/9a1658a1-1b4d-42f5-82cd-ac2af6a092d8) | ![image](https://github.com/Team-Ampersand/Dotori-client-v2/assets/87346613/07ab2bd4-c944-47d5-b84c-a8bed7c376df) |

🔀 기상음악 섬네일 주소 변경

---

src/components/Common/molecules/EmailCheck/index.tsx

회원가입과 비밀번호 찾기 화면에서 이미 회원이라면?과 비밀번호를 변경할 필요가 없다면? 이 바뀌어있었습니다
문구의 위치를 바꿧습니다.

회원가입, 비밀번호 문구 변경

---

src/components/Notice/organisms/NoticeContent/style.ts

https://github.com/Team-Ampersand/Dotori-client-v2/issues/161
Wrapper에 radius를 줬습니다.

Update NoticeWrapper radius

---

src/components/Common/atoms/Inputs/AuthInput/style.ts

자습신청의 filter에 TextField HintText가 잘려나오는 문제가 생겼습니다.
filter에 TextField의 padding과width를 수정하여 고쳤습니다.

🔀: 자습신청 filter textfield 수정

---

src/components/Common/atoms/Inputs/AuthInput/style.ts
src/components/Common/molecules/EmailCheck/index.tsx
src/components/Home/molecules/ProfileImgModal/index.tsx
src/components/StuInfo/organisms/EditModal/style.ts
src/styles/globals.tsx

input 스타일 이슈 발생
- input에 대한 스타일 수정

🔀 input 스타일 수정

---

src/api/member.ts

토큰 재발급이 안되는 이슈 발생
토큰 재발급 요청 헤더 이름 변경

🔀 토큰 재발급 헤더 수정

---

src/components/Home/organisms/MealBoard/index.tsx

급식 시간(조식, 중식, 석식)과 관계없이 무조건 조식부터 뜨는 이슈 발생
급식 api에서 넘겨주는 MMEAL_SC_CODE (조식: 1, 중식: 2, 석식: 3)를 이용해 맞는 급식 시간에 식단표 보이기

🔀 급식 시간에 맞는 식단표 띄우기

---

src/components/Home/molecules/ProfileImgModal/index.tsx

프로필 사진을 변경한 후 새로고침 하던 형식을 수정했습니다.
mutate로 새로고침하지 않고 home data를 바로 수정하도록 했습니다.

🔀 프로필 사진 변경 후 처리 로직 수정

---

src/api/stuInfo.ts
src/components/StuInfo/molecules/EditInput/index.tsx
src/components/StuInfo/molecules/EditInput/style.ts
src/components/StuInfo/molecules/EditRadioBtn/index.tsx
src/components/StuInfo/molecules/EditRadioBtn/style.ts
src/components/StuInfo/organisms/EditModal/index.tsx
src/components/StuInfo/organisms/EditModal/style.ts
src/types/components/StuInfoPage.ts

학생 정보 수정 api 파라미터가 변경됨
- 학생 정보 수정 api 파라미터 변경 (userId -> memberId)
- 학생 정보 수정 스타일 변경
> 기존 화면
> 변경 화면

🔀 학생 정보 수정 api 파라미터 변경 및 스타일 수정

---

src/components/Common/molecules/EmailCheck/index.tsx

24학년도 신입생이 가입해 기존 재학생들의 학번과 겹치는 이슈 발생
회원가입 할 이메일에 `s240`을 포함하면 에러 문구 출력

🔀 24학년도 신입생 이메일 검증 추가

---

src/components/Common/molecules/EmailCheck/index.tsx

24학년도 신입생의 가입을 위해 이메일 검증 삭제
이메일 검증 내용을 삭제했습니다.

🔀 24학년도 신입생 이메일 검증 삭제

---

src/components/Notice/molecules/ContentHeader/index.tsx
src/components/Notice/molecules/ContentHeader/style.ts

Fix notice 

---

next.config.js
src/components/Home/organisms/MealBoard/index.tsx

나이스에서 메뉴를 가져오는 url에 API KEY가 노출되고 있었습니다.
- next.config.js에서 rewrites 사용

🔀 나이스 API KEY 감추기

---

.github/delete_merged_branch-config.yml
.github/workflows/DOTORI_CI.yml

:construction_worker: Add CI build system

---

src/api/notice.ts

공지사항을 작성할 때 이미지를 넣지 않으면 공지사항이 등록되지 않는 오류가 있었습니다.
이미지가 있을 때 없을 때 formData의 값을 각각 설정해줬습니다.

🔀 공지사항 작성 시 오류 수정

---

src/components/Song/molecules/SongItem/index.tsx
src/types/components/SongPage.ts

유튜브 API key가 노출되고 있었습니다.https://github.com/Team-Ampersand/Dotori-client-v2/issues/96
기존에 youtube api key를 사용해 불러오던 title을 서버를 통해 가져오기로 했습니다.

 🔀  youtude api key 노출 방지

---

src/components/Song/molecules/SongForm/index.tsx
src/components/Song/molecules/SongForm/style.ts

- 도토리 음악 신청이 한 사람이 하나 이상을 신청 할 수 있는 문제가 있었습니다.
- 음악 신청 버튼 스타일 변경
- submit 버튼의 동작이 success일 때 0.3초의 디바운스를 걸어 방지 하였습니다.
- input value가 정규식에 맞을 때 버튼의 스타일이 활성화 되게 수정하였습니다.

🔀 도토리 다중 음악 신청 방지

---

next.config.js
src/components/Song/molecules/SongForm/index.tsx

input의 url을 붙여넣기 한 후 엔터를 누르면 '아무것도 입력하지 않았습니다'가 출력되는 이슈
input의 url을 붙여넣기 한 후 엔터를 눌렀을 때 음악이 개시되게 변경 했습니다.
input의 조건식을 확인하는 onChange 함수를 register 객체 안으로 이동 시켰습니다.

기상 음악 신청 불가 이슈 

---

src/components/Song/molecules/SongForm/index.tsx

기상음악 신청 로직을 변경 하였습니다.
lodash의 디바운스로직을 제거하고 react-hook-form의 isSubmitting을 사용하였습니다.

🔀 다중 음악 방지 방식 isSubmitting 사용

---

src/components/Home/organisms/MealBoard/index.tsx
src/types/Meal.ts

기존 날짜를 변경하는 것이 아닌 조식 중식 석식을 변경해도 api가 호출되는 문제가 있었습니다.
- api를 호출하여 state에 저장 후 useEffect로 조식, 중식, 석식이 아닌 요일이 바뀔때만 api를 호출하게 변경 했습니다.

🔀 나이스 meal api 통신 수정

---

src/hooks/useToastify.ts
src/pages/_app.tsx

유지보수적인 면이나 파일마다 react-toastify 라이브러리를 불러왔습니다.
- type과 message만 전달받아 toast를 띄우는 custom hooks 제작

🔀 react-toastify custom hooks 제작

---

src/api/notice.ts
src/components/Notice/organisms/NoticeContent/index.tsx
src/components/Notice/organisms/NoticeList/index.tsx

공지 리스트에서 key값이 없어 오류 발생
key값 추가

:bug: Fix warning

---

src/pages/notice/[boardId].tsx
src/pages/notice/index.tsx

사이드 바 이동 시 특정 페이지에서 사이드 바의 반응형이 달라지는 문제가 발생했습니다.
issue: #270 
공지사항 페이지의 구조가 다른 페이지에서 공통적으로 사용하는 스타일을 사용하지 않아서 발생한 문제였습니다.

🔀 사이드바 반응형 문제 해결

---

src/utils/canvas.ts

서버에서 Validation을 추가하여 서버가 확장자를 확인할 수 있도록 반영합니다.
issue: #278 
- new File 생성자 사용
- image/jpeg으로 확정하는 게 아니라 이미지 원본 확장자로 보내기

🔀 프로필 이미지 확장자를 서버에서 확인할 수 있도록 변경

---

src/components/Home/atoms/Script/SomeScript.tsx
src/components/Home/molecules/ChannelBtn/index.tsx
src/pages/_app.tsx
src/pages/home.tsx
src/types/common/window.d.ts

채널톡 스크립트 코드를 추가한 이후 토큰에 영향을 주고 있는 것 같습니다.

Revert 🔀:  로그인 화면에 채널톡 아이콘 문제 해결

---

src/components/Song/molecules/NoticeModal/index.tsx

🔀 Update Song Notice

---

.github/workflows/DOTORI_CI.yml
src/components/Common/atoms/Calendar/index.tsx
src/components/Penalty/molecules/PenaltyRecordModal/index.tsx
src/components/Song/organisms/SongModal/index.tsx
src/components/Song/organisms/SongRightLayer/index.tsx

calendar의 날짜가 이상하게 표시되는 오류가 있습니다
- dynamic import 추가
- CI content 변경

🔀 calendar 날짜 표시 이슈
